Additional resource to Frontend Project
WeMakeDevs/roadmaps pull request #346
Opened 2023-01-11 09:57 UTC by muhammadiqbalid83

## Fixes Issue

## Changes proposed

## Screenshots

## Note to reviewers

2023-01-11 10:51 UTC, shivaabhishek07 reviewed
What additional resources you have added?

2023-01-11 11:15 UTC, muhammadiqbalid83 commented
this : https://devchallenges.io/

2023-01-11 11:47 UTC, shivaabhishek07 commented
> this : https://devchallenges.io/

Ok!

2023-01-12 18:15 UTC, siddhant-khisty requested changes

2023-01-12 18:15 UTC, siddhant-khisty commented on Frontend-Development/README.md
> +
remove whitespace ONLY for line 50

2023-01-12 18:15 UTC, siddhant-khisty commented on Frontend-Development/README.md
> +
Remove whitespace ONLY for like 66

2023-01-12 18:19 UTC, kaiwalyakoparkar requested changes
Please resolve the lint error

2023-02-24 19:34 UTC, siddhant-khisty commented
Closing due to inactivity

2023-02-24 19:34 UTC, closed without merging