Added Youtube tutorial on Docker
WeMakeDevs/roadmaps pull request #467
Opened 2023-03-22 17:52 UTC by tarunclub

## Fixes Issue

## Changes proposed

## Screenshots

## Note to reviewers

2023-03-22 18:27 UTC, TRohit20 approved these changes
I observed that you closed a PR where I asked you to make this change and opened a new PR with the suggested change. Next time, don't open a new PR when asked to make changes, you always have the option to make changes in the branch you're working in and directly push them upstream to the PR you opened. :)

2023-03-23 01:50 UTC, tarunclub commented
@TRohit20 sure I will keep that in mind : )

2023-03-23 05:53 UTC, siddhant-khisty requested changes

2023-03-23 05:53 UTC, siddhant-khisty commented on DevOps/Readme.md
> +  - [A practical guide on Docker - Hitesh Choudhary(Youtube)](https://www.youtube.com/watch?v=rr9cI4u1_88&t=4594s)
```suggestion
  - [A practical guide on Docker - Hitesh Choudhary(Youtube)](https://www.youtube.com/watch?v=rr9cI4u1_88)
```
Remove the timestamp

2023-03-24 10:10 UTC, Sandeep-RN requested changes
And I think we can also use the full name of the video "A practical guide on Docker with projects" it will be helpful for those people who are searching for Docker projects as well.

2023-06-02 14:59 UTC, closed without merging