Update Readme.md
WeMakeDevs/roadmaps pull request #506
Opened 2023-04-15 01:03 UTC by itanand

I have added some of the new Resources like Github, and Python . For the DevOps Python and Version Control System is Very Important.

## Fixes Issue

## Changes proposed

In DevOps Roadmap I have make these Changes - I have added some of the new Resources like Github, and Python . For the DevOps Python and Version Control System is Very Important.

## Screenshots

![image](https://user-images.githubusercontent.com/38817976/232175463-08496bf1-016d-417b-9aac-782f9b5e76a8.png)

## Note to reviewers

In DevOps Roadmap I have make these Changes - > I have added some of the new Resources like Github, and Python . For the DevOps Python and Version Control System is Very **Important.**

2023-04-15 02:32 UTC, Sandeep-RN requested changes
It looks good,
But I would suggest you to move "Version Control System - Git & GitHub" section to after "Operating System Basics" so that it follows an order, new learners will have difficult time understanding Git & GitHub.

and Python can also be moved to after "GoLang" or in between "Operating System Basics" and "Version Control System - Git & Github" this is just optional you can leave it at the top as well I don't think it would make a big difference.

2023-04-15 02:56 UTC, itanand commented
Yeah Sure, I can do that

On Sat, 15 Apr 2023, 08:02 Sandeep R N, ***@***.***> wrote:

> ***@***.**** requested changes on this pull request.
>
> It looks good,
> But I would suggest you to move "Version Control System - Git & GitHub"
> section to after "Operating System Basics" so that it follows an order, new
> learners will have difficult time understanding Git & GitHub.
>
> and Python can also be moved to after "GoLang" or in between "Operating
> System Basics" and "Version Control System - Git & Github" this is just
> optional you can leave it at the top as well I don't think it would make a
> big difference.
>
> —
> Reply to this email directly, view it on GitHub
> <https://github.com/WeMakeDevs/roadmaps/pull/506#pullrequestreview-1386294559>,
> or unsubscribe
> <https://github.com/notifications/unsubscribe-auth/AJIFBOANAUHLI67USNJJ63TXBICDTANCNFSM6AAAAAAW7B5CMQ>
> .
> You are receiving this because you authored the thread.Message ID:
> ***@***.***>
>

2023-04-22 02:47 UTC, siddhant-khisty requested changes
Suggested a couple of changes. Overall great work.

2023-04-22 02:47 UTC, siddhant-khisty commented on DevOps/README.md
> +Visit the following resources to learn more:
No need for this intro paragaph

2023-04-22 02:47 UTC, siddhant-khisty commented on DevOps/README.md
> +- [Automate your Workflow with GitHub Actions](https://www.youtube.com/watch?v=nyKZTKQS_EQ)
Please keep it the exact name of the resource. The resource name is not `GitHub Awesome Explanation` :)

2023-04-22 02:47 UTC, siddhant-khisty commented on DevOps/README.md
> +
We can exclude python since for cloud-native workloads golang is preferred for it's performance with cloud-based workloads

2023-06-02 14:59 UTC, closed without merging