Updating Geek Around Community Discord Name
WeMakeDevs/roadmaps pull request #515
Opened 2023-04-20 15:39 UTC by Sandeep-RN

## Changes proposed

Updating Geek Around Community Discord Name to "Geek Around Community X Cloud Native Nashik "

## Screenshots

![image](https://user-images.githubusercontent.com/42804812/233416722-27c688f4-c885-46b8-a975-35980b3e9e95.png)

2023-04-20 16:52 UTC, kaiwalyakoparkar requested changes

2023-04-20 16:52 UTC, kaiwalyakoparkar commented on DevRel/Communities/Readme.md
> +- [Geek Around Community X Cloud Native Nashik](https://discord.io/geekaroundcommunity)
Update the link to `https://community.kaiwalyakoparkar.com/`

2023-04-20 16:53 UTC, kaiwalyakoparkar commented
Also, this could be changed in other roadmaps too. You can go ahead with updating those if you want :)

2023-04-21 09:27 UTC, Sandeep-RN commented
Hello @kaiwalyakoparkar, 
I have updated the link, please review this PR and check if everything is ok.

And I'll be changing this in other roadmaps too so please keep an eye on those too.

Thanks😊.

2023-04-21 15:02 UTC, merged