Update README.md
WeMakeDevs/roadmaps pull request #546
Opened 2023-05-18 01:42 UTC by VishwaS-22

## Fixes Issue

Closes #545

## Changes proposed

Removed duplicate link.

Happy to contribute. Thankyou!

2023-05-18 01:58 UTC, siddhant-khisty requested changes

2023-05-18 01:58 UTC, siddhant-khisty commented on DevOps/README.md
>    - [Complete Docker Course - From BEGINNER to PRO! (Learn Containers)](https://www.youtube.com/watch?v=RqTEHSBrYFw&t=3615s)
Please add the channel name as well, as that we can avoid duplicate resources in the future.
```suggestion
  - [Complete Docker Course - From BEGINNER to PRO! (Learn Containers) - by DevOps Directive](https://www.youtube.com/watch?v=RqTEHSBrYFw&t=3615s)
```

2023-05-18 12:21 UTC, VishwaS-22 commented
Hey @siddhant-khisty! Updated the requested changes!
Thankyou!

2023-05-18 12:38 UTC, Sandeep-RN approved these changes
LGTM

2023-05-18 14:44 UTC, siddhant-khisty approved these changes
lgtm

2023-05-18 14:45 UTC, merged

2023-05-21 09:55 UTC, VishwaS-22 commented
Hey @siddhant-khisty! Thanks for merging it. 

Happy to contribute to the community.