Update README.md
WeMakeDevs/roadmaps pull request #609
Opened 2023-07-15 14:54 UTC by KUNDAN1334

i just numbered the links so that confusion can be reduced and add alt resource to same content.

## Fixes Issue #600 

## Changes proposed
I just numbered the link and content so that confusion can be reduced and also write alt resource to same content.

1. numbered the content
2. provide alt resource tag

## Screenshots

## Note to reviewers

2023-07-15 15:19 UTC, FlashBang-000X approved these changes

2023-07-16 04:19 UTC, KUNDAN1334 commented
after reviewed why this showing review required

2023-07-18 18:56 UTC, siddhant-khisty requested changes

2023-07-18 18:56 UTC, siddhant-khisty commented on Frontend-Development/README.md
> +- [8] [What is DNS? | How DNS works](https://www.cloudflare.com/en-gb/learning/dns/what-is-dns/)
These numbers are not required. Rather the way you have mentioned Alt resources in the CSS section seems like a much better way to go about it

2023-07-18 18:56 UTC, siddhant-khisty commented on Frontend-Development/README.md
> +- [13] [CSS Diner](https://flukeout.github.io/)
Please remove the numbers. Only keep the `ALT RESOURCE` part

2023-07-19 07:12 UTC, siddhant-khisty commented
Hey @KUNDAN1334 There have been some updates with regard to this issue. Please have a look over at #600 for the same

2023-08-18 14:57 UTC, AmanKumarVerma11 approved these changes

2023-08-21 15:35 UTC, closed without merging